### ISSUE TITLE
Dependency factory class

### ISSUE THREAD

**Issue by AmroAbdrabo** [Zeavee/Run0rD1e#199]
Hello Louis and Alex, 
I was wondering if it's okay if we have just one class which provides all the dependencies publicly and statically. That way we can access the same dependency without worrying about activity-to-activity communication

**Comment by zyuiop** [comment]
Hello,
I don't really see how your suggestion would help. Most of your dependencies should not be related to activities anyway - and if they are, then moving them to a public static field won't help, as they won't be initialized before that activity launches (which is the same problem). I believe that most of your dependencies can either be passed via a constructor parameter, or be singleton by themselves. For example, the ApplicationDatabase can be a singleton, and it doesn't need to be tied to an activity. Moving it to a big singleton would completely break separation of concerns and is therefore not recommended at all.
Cheers,
Louis
