### ISSUE TITLE
Accessing the application before the activity is created

### ISSUE THREAD

**Issue by Zeavee** [Zeavee/Run0rD1e#217]
Hello, 

I used the link you gave us to do dependency injection. I did not have enough time to go deep into Dagger, so I chose to use the manual dependency injection.

The problem is that in instrumented tests, we cannot access the application until it is created. Since the dependencies are set in the onCreate() method, we have a problem when we want to set them in the tests. We would need to override the beforeActivityLaunched method to inject the dependencies at this point, but the getActivity() call returns null here. 

```java
    @Rule
    public final ActivityTestRule<LoginFormActivity> mActivityRule =
            new ActivityTestRule<LoginFormActivity>(LoginFormActivity.class) {
                @Override
                protected void beforeActivityLaunched() {
                    AppContainer appContainer = ((MyApplication) mActivityRule.getActivity().getApplication()).appContainer;
                    appContainer.authenticationAPI = new MockAuthenticationAPI(registeredUsers, null);
                }
            };
```

If we do this in the `@Before` annotated method, it is too late and the dependency is already initialized.

The only way we found for now is to go back and forth between activities to run onCreate afterwards, but I am sure there is a better way.

**Comment by zyuiop** [comment]
Hi !

Can you please try to follow the instructions here https://developer.android.com/training/testing/junit-runner#app-context ?
They provide a way to access the Application Context (and therefore the app container) without relying on the activity. You should therefore be able to call that in @Before.

Let me know if it doesn't work.
Cheers,
Louis

**Comment by Zeavee** [comment]
It worked fine thank you!
